task: hellaswag_local
dataset_path: parquet
dataset_name: null
dataset_kwargs:
  data_files:
    train: datasets/hellaswag/train-00000-of-00001.parquet
    validation: datasets/hellaswag/validation-00000-of-00001.parquet
output_type: multiple_choice
training_split: train
validation_split: validation
test_split: null
process_docs: !function hellaswag_utils.process_docs
doc_to_text: "{{query}}"
doc_to_target: "{{label}}"
doc_to_choice: choices
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
